# MySQL.  Versions 4.1 and 5.0 are recommended.

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: branchapp_development
  pool: 5
  username: root
  password:
  host: 127.0.0.1

# this is used for offline use only
local_stage:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: branchapp_development
  pool: 5
  username: root
  password:
  host: 127.0.0.1

# Warning: The database defined as "test" will be erased and
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: branchapp_test
  pool: 5
  username: root
  password:
  host: 127.0.0.1

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>